name: Release

on:
  push:
    tags:
      - 'release/*'

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: echo "release=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for linux64
      run: yarn gulp release --linux64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-release-linux-${{ env.release }}
        path: release/rotorflight-configurator*


  macos:

    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: echo "release=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for MacOS
      run: yarn gulp release --osx64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-release-macos-${{ env.release }}
        path: release/rotorflight-configurator*


  windows:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: |
        $snapshot = $env:GITHUB_REF -replace '.*/',''
        echo "release=$snapshot" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Initialise build environment
      run: yarn install

    - name: Build release for windows
      run: yarn gulp release --win32

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-configurator-release-windows-${{ env.release }}
        path: release/rotorflight-configurator*


  release:

    runs-on: ubuntu-latest

    needs: [linux, windows, macos]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set build variables
      run: echo "release=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Download Linux Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-release-linux-${{ env.release }}

    - name: Download MacOS Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-release-macos-${{ env.release }}

    - name: Download Windows Artifacts
      uses: actions/download-artifact@v2
      with:
        name: rotorflight-configurator-release-windows-${{ env.release }}

    - name: Create Release
      run: |
        set -x
        assets=()
        for file in rotorflight-configurator*
        do
          assets+=("-a" "$file")
        done
        tag="${GITHUB_REF##*/}"
        (
          echo "Rotorflight Configurator v${tag}"
          echo
          cat Release.md
        ) | hub release create "${assets[@]}" -F - "${GITHUB_REF}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

