name: Testing

on:
  push:
    tags:
      - 'testing/*'


jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Update version number
      run: make version SEMVER=${{ env.GIT_VER }}

    - name: Initialise build environment
      run: make init

    - name: Build release for linux64
      run: yarn gulp redist --platform linux --arch x86_64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-configurator-linux-testing-${{ env.GIT_VER }}
        path: redist/*


  macos:

    runs-on: macos-12

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Update version number
      run: make version SEMVER=${{ env.GIT_VER }}

    - name: Initialise build environment
      run: make init

    - name: Build release for MacOS
      run: yarn gulp redist --platform osx --arch x86_64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-configurator-macos-testing-${{ env.GIT_VER }}
        path: redist/*


  win64:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Set build variables
      run: |
        $GIT_VER = $env:GITHUB_REF -replace '.*/',''
        echo "GIT_VER=$GIT_VER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Update version number
      run: make version SEMVER=${{ env.GIT_VER }}

    - name: Initialise build environment
      run: make init

    - name: Build release for windows
      run: yarn gulp redist --platform win --arch x86_64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-configurator-win64-testing-${{ env.GIT_VER }}
        path: redist/*


  win32:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Set build variables
      run: |
        $GIT_VER = $env:GITHUB_REF -replace '.*/',''
        echo "GIT_VER=$GIT_VER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Update version number
      run: make version SEMVER=${{ env.GIT_VER }}

    - name: Initialise build environment
      run: make init

    - name: Build release for windows
      run: yarn gulp redist --platform win --arch x86

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-configurator-win32-testing-${{ env.GIT_VER }}
        path: redist/*


  android:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9123335
        packages: 'tools platform-tools platforms;android-34'

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Update version number
      run: make version SEMVER=${{ env.GIT_VER }}

    - name: Initialise build environment
      run: make init

    - name: Build release for Android
      run: yarn gulp redist --platform android

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-configurator-android-testing-${{ env.GIT_VER }}
        path: redist/*


  cleanup:

    runs-on: ubuntu-latest

    needs: [linux, macos, win64, win32, android]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Delete tag
      run: git push origin :${GITHUB_REF}

